/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AwcSpinner {}
  interface AwcStockFinder {}
  interface AwcStockPrice {
    'stockSymbol': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLAwcSpinnerElement extends Components.AwcSpinner, HTMLStencilElement {}
  var HTMLAwcSpinnerElement: {
    prototype: HTMLAwcSpinnerElement;
    new (): HTMLAwcSpinnerElement;
  };

  interface HTMLAwcStockFinderElement extends Components.AwcStockFinder, HTMLStencilElement {}
  var HTMLAwcStockFinderElement: {
    prototype: HTMLAwcStockFinderElement;
    new (): HTMLAwcStockFinderElement;
  };

  interface HTMLAwcStockPriceElement extends Components.AwcStockPrice, HTMLStencilElement {}
  var HTMLAwcStockPriceElement: {
    prototype: HTMLAwcStockPriceElement;
    new (): HTMLAwcStockPriceElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'awc-spinner': HTMLAwcSpinnerElement;
    'awc-stock-finder': HTMLAwcStockFinderElement;
    'awc-stock-price': HTMLAwcStockPriceElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AwcSpinner {}
  interface AwcStockFinder {
    'onAwcSymbolSelected'?: (event: CustomEvent<string>) => void;
  }
  interface AwcStockPrice {
    'stockSymbol'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'awc-spinner': AwcSpinner;
    'awc-stock-finder': AwcStockFinder;
    'awc-stock-price': AwcStockPrice;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'awc-spinner': LocalJSX.AwcSpinner & JSXBase.HTMLAttributes<HTMLAwcSpinnerElement>;
      'awc-stock-finder': LocalJSX.AwcStockFinder & JSXBase.HTMLAttributes<HTMLAwcStockFinderElement>;
      'awc-stock-price': LocalJSX.AwcStockPrice & JSXBase.HTMLAttributes<HTMLAwcStockPriceElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


